#!/usr/bin/env bash

# shellcheck disable=SC1091
# shellcheck source=./setup.conf

pacman -Sy --noconfirm
pacman -S --noconfirm --needed terminus-font
fc-cache -fv >/dev/null 2>&1
setfont ter-v22b
clear
# Find the name of the folder the scripts are in
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

CONFIG_FILE="$SCRIPT_DIR"/setup.conf

LOG="$SCRIPT_DIR"/main.log
[[ -f "$LOG" ]] && rm -f "$LOG"

logo() {
    echo -ne "
-----------------------------------------------------------------
         .8.            d888888o.           .8.           8 8888
        .888.         .'8888:' '88.        .888.          8 8888
       :88888.        8.'8888.   Y8       :88888.         8 8888
      . '88888.       '8.'8888.          . '88888.        8 8888
     .8. '88888.       '8.'8888.        .8. '88888.       8 8888
    .8'8. '88888.       '8.'8888.      .8'8. '88888.      8 8888
   .8' '8. '88888.       '8.'8888.    .8' '8. '88888.     8 8888
  .8'   '8. '88888.  8b   '8.'8888.  .8'   '8. '88888.    8 8888
 .888888888. '88888. '8b.  ;8.'8888 .888888888. '88888.   8 8888
.8'       '8. '88888. 'Y8888P ,88P'.8'       '8. '88888.  8 8888
-----------------------------------------------------------------
                Archlinux System Automated Installer
-----------------------------------------------------------------
"
}

copy_logs() {
    echo "Copying logs"
    cp -v "$LOG" "$MOUNTPOINT"/var/log/asai.log
}

do_reboot() {
    echo "unmounting $MOUNTPOINT"
    if [[ "$LVM" -eq "1" || "$LUKS" -eq "1" ]]; then
        i=0
        while [[ "$i" -le "${#LVM_NAMES[@]}" ]]; do
            umount -l /dev/"$LVM_VG"/"${LVM_NAMES[$i]}"
        done
    fi
    umount -R "$MOUNTPOINT"/boot
    umount -R "$MOUNTPOINT"
    echo "Rebooting..."
    reboot
}

end() {
    REBOOT="true"
    copy_logs
    for ((i = 15; i >= 1; i--)); do
        read -r -s -n 1 -t 1 -p "ASAI is rebooting in $i seconds... Press Esc key to abort or press R key to reboot now."$'\n' KEY
        CODE="$?"
        if [ "$CODE" != "0" ]; then
            continue
        fi
        if [[ "$KEY" == $'\e' ]]; then
            REBOOT="false"
            break
        elif [[ "$KEY" == "r" || "$KEY" == "R" ]]; then
            REBOOT="true"
            break
        fi
    done
    if [[ "$REBOOT" == "true" ]]; then
        do_reboot
    else
        echo "Reboot is aborted "
    fi
}

sequence() {
    echo -ne "Starting asai...\n"
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
    else
        echo "ERROR! Missing file: setup.conf"
        exit 0
    fi
    . "$SCRIPT_DIR"/scripts/0-preinstall
    arch-chroot "$MOUNTPOINT" /root/asai/scripts/1-setup
    arch-chroot "$MOUNTPOINT" /usr/bin/runuser -u "$USERNAME" -- /home/"$USERNAME"/asai/scripts/2-user
    arch-chroot "$MOUNTPOINT" /root/asai/scripts/scripts/3-post-setup
    logo
    echo -ne "
            Done - Please Eject Install Media and Reboot\n\n"

}
logo
echo -ne "
            Scripts are in directory named asai\n\n"
. "$SCRIPT_DIR"/scripts/startup
sequence |& tee "$LOG"
end
