#!/usr/bin/env bash
# shellcheck disable=SC1091,SC1090

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

CONFIG_FILE="$SCRIPT_DIR"/configs/setup.conf
FUNC_FILE="$SCRIPT_DIR"/configs/shared
LOG_FILE="$SCRIPT_DIR"/configs/main.log

[[ -f "$LOG_FILE" ]] && rm -f "$LOG_FILE"

source_file() {
    if [[ -f "$1" ]]; then
        source "$1"
    else
        echo "ERROR! Missing file: $1"
        exit 0
    fi
}

sequence() {
    clear
    title "Starting ASAI..."
    source_file "$CONFIG_FILE"
    . "$SCRIPT_DIR"/scripts/0-preinstall
    arch-chroot "$MOUNTPOINT" /root/asai/scripts/1-setup
    if [[ "$DESKTOP" != "minimal" ]]; then
        arch-chroot "$MOUNTPOINT" /usr/bin/runuser -u "$USERNAME" -- /home/"$USERNAME"/asai/scripts/2-user
        arch-chroot "$MOUNTPOINT" /root/asai/scripts/3-postinstall
    else
        sudo_password "$MOUNTPOINT/etc/sudoers"
    fi
    logo
    title "Done - Please Eject Install Media and Reboot"

}

source_file "$FUNC_FILE"
background_checks
start_jobs
clear
logo
title "Scripts are in directory named asai"
. "$SCRIPT_DIR"/scripts/startup
sequence |& tee "$LOG_FILE"
end
