#!/usr/bin/env bash
# shellcheck disable=SC1091,SC1090

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

LOG_FILE="$SCRIPT_DIR"/configs/main.log
CONFIG_FILE="$SCRIPT_DIR"/configs/setup.conf

[[ -f "$LOG_FILE" ]] && rm -f "$LOG_FILE"

source_setup() {
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
    else
        echo "ERROR! Missing file: $CONFIG_FILE"
        exit 0
    fi
}

sequence() {
    clear
    . "$SCRIPT_DIR"/scripts/0-preinstall
    arch-chroot "$MOUNTPOINT" /root/asai/scripts/1-setup
    if [[ "$DESKTOP" != "minimal" ]]; then
        arch-chroot "$MOUNTPOINT" /usr/bin/runuser -u "$USERNAME" -- /home/"$USERNAME"/asai/scripts/2-user
        arch-chroot "$MOUNTPOINT" /root/asai/scripts/3-postinstall
    else
        sudo_password "$MOUNTPOINT/etc/sudoers"
    fi
    end
    logo
    title "Done - Please Eject Install Media and Reboot"

}

source_setup
background_checks
start_jobs
clear
logo
title "Scripts are in directory named asai"
if [[ "$AUTO" -eq "0" ]]; then
    . "$SCRIPT_DIR"/scripts/startup
fi
if [[ "$LOG" -eq "1" ]]; then
    sequence |& tee "$LOG_FILE"
else
    sequence
fi
