#!/usr/bin/env bash

make_boot() {
    if [[ "$UEFI" -eq "1" ]]; then
        mkfs.vfat -F32 -n "$BOOT" "$PART1"
    fi
}

do_btrfs() {
    mkfs.btrfs -L "$1" "$2" -f
    mount -t btrfs "$2" "$MOUNTPOINT"

    echo "Creating subvolumes and directories"
    for x in "${BTRFS_SUBVOLUMES[@]}"; do
        btrfs subvolume create "$MOUNTPOINT"/"${x}" >/dev/null 2>&1
    done

    umount /mnt
    mount -o "$MOUNTOPTION",subvol=@ "$2" "$MOUNTPOINT"

    for z in "${BTRFS_SUBVOLUMES[@]:1}"; do
        w="${z[*]//@/}"
        mkdir /mnt/"${w}"
        mount -o "$MOUNTOPTION",subvol="${z}" "$2" "$MOUNTPOINT"/"${w}"
    done
    set_option "PACKAGES" "btrfs-progs"
}

do_format() {
    echo "$FILE_SYSTEM setup"
    case "$FILE_SYSTEM" in
    "xfs")
        set_option "PACKAGES" "xfsprogs"
        mkfs.xfs -f -L "$ROOT" "$1"
        ;;
    "btrfs")
        set_option "PACKAGES" "btrfs-progs"
        mkfs.btrfs -L "$ROOT" "$1" -f
        ;;
    "ext4")
        mkfs.ext4 -E discard -F -L "$ROOT" "$1"
        ;;
    "vfat")
        mkfs.vfat -F32 "$1"
        ;;
    "f2fs")
        set_option "PACKAGES" "f2fs-tools"
        mkfs.f2fs -l "$ROOT" -O extra_attr,inode_checksum,sb_checksum "$1"
        ;;
    "ext2")
        mkfs.ext2 -L "$ROOT" "$1"
        ;;
    "ext3")
        mkfs.ext3 -L "$ROOT" "$1"
        ;;
    "jfs")
        set_option "PACKAGES" "jfsutils"
        mkfs.jfs -L "$ROOT" "$1"
        ;;
    "nilfs2")
        set_option "PACKAGES" "nilfs-utils"
        mkfs.nilfs2 -L "$ROOT" "$1"
        ;;
    "ntfs")
        set_option "PACKAGES" "ntfs-3g"
        mkfs.ntfs -Q -L "$ROOT" "$1"
        ;;
    *)
        echo "ERROR! Unsupported filesystem"
        exit 0
        ;;
    esac

}

do_lvm() {
    i=0
    while [[ "$i" -lt "$LVM_PART_NUM" ]]; do

        if [[ "$p" -eq "1" || "$LVM_PART_NUM" -eq "1" ]]; then
            lvcreate --extents 100%FREE "$LVM_VG" --name "${LVM_NAMES[$i]}"
        else
            lvcreate --size "${LVM_SIZES[$i]}" "$LVM_VG" --name "${LVM_NAMES[$i]}"
        fi
        i=$((i + 1))
        p=$((LVM_PART_NUM - 1))
    done
}

mount_lvm() {
    vgchange -ay &>/dev/null
    i=0
    while [[ "$i" -le "$LVM_PART_NUM" ]]; do
        lvchange -ay /dev/"$LVM_VG"/"${LVM_NAMES[$i]}" >/dev/null 2>&1
        do_format /dev/"$LVM_VG"/"${LVM_NAMES[$i]}" 

        i=$((i + 1))
    done
    mount -t "$FILE_SYSTEM" /dev/"$LVM_VG"/"${LVM_NAMES[0]}" "$MOUNTPOINT"
    for x in "${LVM_NAMES[@]:1}"; do
        mkdir "$MOUNTPOINT"/"$x"
        mount -t "$FILE_SYSTEM" /dev/"$LVM_VG"/"$x" "$MOUNTPOINT"/"$x"
    done
}

prep_disk() {
    echo "Preparing disk"
    wipefs -a -f "$DISK"
    sgdisk -Z "$DISK"
    sgdisk -a 2048 -o "$DISK"
}

do_partition() {
    prep_disk
    echo "Partitioning disk"
    if [[ "$UEFI" -eq "1" ]]; then
        sgdisk -n 1::+300M --typecode=1:ef00 --change-name=1:"$BOOT" "$DISK"
        sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:"$ROOT" "$DISK"
    else
        sgdisk -n 1::+1M --typecode=1:ef02 --change-name=1:"BIOSBOOT" "$DISK"
        sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:"$ROOT" "$DISK"

    fi
}

mount_boot() {
    if [[ "$UEFI" -eq "1" ]]; then
        echo "Mounting boot partition"
        mkdir "$MOUNTPOINT"/boot
        mount -t vfat -L EFIBOOT "$MOUNTPOINT"/boot/
    fi
}

title "Preinstall setup"
install_pkg pacman-contrib reflector rsync gptfdisk
echo "Modifying pacman.conf"
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf

if [[ ! -f /etc/pacman.d/mirrorlist.backup ]]; then
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
fi
echo "Generating new mirrorlist"
reflector --age 48 --country "$ISO" -f 5 --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
mkdir "$MOUNTPOINT" &>/dev/null

if [[ "$SDD" -eq "1" ]]; then
    PART1=${DISK}p1
    PART2=${DISK}p2
else
    PART1=${DISK}1
    PART2=${DISK}2
fi

set_option "PART2" "$PART2"

case "$LAYOUT" in
"btrfs")
    do_partition
    make_boot
    do_btrfs "$ROOT" "$PART2"
    mount_boot
    ;;

"lvm")
    set_option "PACKAGES" "lvm2"
    do_partition
    sgdisk --typecode=2:8e00 "$DISK"
    partprobe "$DISK"
    make_boot
    pvcreate "$PART2"
    vgcreate "$LVM_VG" "$PART2"
    do_lvm
    mount_lvm
    mount_boot
    set_option "HOOKS" "(lvm2 filesystems)"
    ;;

"luks")
    set_option "PACKAGES" "lvm2 cryptsetup"
    do_partition
    make_boot
    echo -n "$LUKS_PASSWORD" | cryptsetup -y -v luksFormat "$PART2" -
    echo -n "$LUKS_PASSWORD" | cryptsetup open "$PART2" luks -
    pvcreate "$LUKS_PATH"
    vgcreate "$LVM_VG" "$LUKS_PATH"
    do_lvm
    mount_lvm
    mount_boot
    ;;

"none")
    modprobe dm-mod
    vgscan &>/dev/null
    vgchange -ay &>/dev/null
    mount "$ROOT_PARTITION" "$MOUNTPOINT"
    if [[ "$UEFI" -eq 1 ]]; then
        mount_boot
    fi
    ;;

*)
    echo "ERROR! Unsupported Partition layout"
    exit 0
    ;;
esac

if mount_check; then
    echo -ne "ERROR! Not mounted\n"
    exit 0
else
    echo -ne "Mounting rechecked\n"
fi

echo "Starting pacstrap"
pacstrap "$MOUNTPOINT" "${PACKAGES[@]}" --noconfirm --needed >/dev/null 2>&1
echo "Registering keyserver"
echo "keyserver hkp://keyserver.ubuntu.com" >>"$MOUNTPOINT"/etc/pacman.d/gnupg/gpg.conf

echo "Generating fstab"
genfstab -U "$MOUNTPOINT" >>"$MOUNTPOINT"/etc/fstab

cp -R "$SCRIPT_DIR" "$MOUNTPOINT"/root/asai
cp /etc/pacman.d/mirrorlist "$MOUNTPOINT"/etc/pacman.d/mirrorlist

if [[ $TOTALMEM -lt 8000000 ]]; then
    echo "Creating swap file "
    mkdir -p "$MOUNTPOINT"/opt/swap
    if [[ "$LAYOUT" =~ "btrfs" ]]; then
        echo "Setting COW"
        chattr +C "$MOUNTPOINT"/opt/swap
    fi
    dd if=/dev/zero of="$MOUNTPOINT"/opt/swap/swapfile bs=1M count=2048 status=progress >/dev/null 2>&1
    echo "Setting permissions"
    chmod 600 "$MOUNTPOINT"/opt/swap/swapfile
    chown root "$MOUNTPOINT"/opt/swap/swapfile
    echo "Making swap on"
    mkswap "$MOUNTPOINT"/opt/swap/swapfile >/dev/null 2>&1
    swapon "$MOUNTPOINT"/opt/swap/swapfile >/dev/null 2>&1
    echo -e "/opt/swap/swapfile\tnone     \tswap     \tsw\t0 0" >>"$MOUNTPOINT"/etc/fstab
fi
