#!/usr/bin/env bash
# shellcheck disable=SC1090

SCRIPT_DIR="$HOME/asai"

CONFIG_FILE="$SCRIPT_DIR"/configs/setup.conf
FUNC_FILE="$SCRIPT_DIR"/configs/shared

source_file() {
    if [[ -f "$1" ]]; then
        source "$1"
    else
        echo "ERROR! Missing file: $1"
        exit 0
    fi
}

source_file "$CONFIG_FILE"
source_file "$FUNC_FILE"

install_pkg vim dhclient reflector \
    base-devel wget rsync git pacman-contrib \
    curl efibootmgr

install_xorg() {
    install_pkg xorg xorg-server xorg-xinit
}

install_services() {
    install_pkg cups bluez bluez-utils networkmanager cronie ntp dhcpcd
}

if [[ $TOTALMEM -gt 8000000 ]]; then
    echo "Changing makepkg.conf for $CPU cores"
    sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$CPU\"/g" /etc/makepkg.conf
    sed -i "s/COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T $CPU -z -)/g" /etc/makepkg.conf
fi

echo "Setup Language and set locale"
echo "${LOCALE//\"/}" >>/etc/locale.gen

hwclock --systohc

locale-gen
timedatectl --no-ask-password set-timezone "$TIMEZONE"
timedatectl --no-ask-password set-ntp 1
localectl --no-ask-password set-locale LANG="$LOCALE" LC_TIME="$LOCALE"
localectl --no-ask-password set-keymap --no-convert "$KEYMAP"

sudo_no_password "/etc/sudoers"

echo "Installing desktop: $DESKTOP"
case "$DESKTOP" in
"kde")
    install_pkg plasma kf5 sddm plasma-wayland-session
    systemctl enable sddm.service
    ;;
"gnome")
    install_xorg
    install_pkg gnome gnome-extra gnome-software gnome-initial-setup gnome-tweak-tool gnome-power-manager
    install_services
    systemctl enable gdm.service
    ;;
"xfce")
    install_xorg
    install_pkg xfce4 xfce4-goodies lightdm lightdm-gtk-greeter pavucontrol pulseaudio
    install_services
    systemctl enable lightdm.service
    ;;
"mate")
    install_xorg
    install_pkg mate mate-extra lightdm lightdm-gtk-greeter
    install_services
    systemctl enable lightdm.service
    ;;
"lxqt")
    install_xorg
    install_pkg lxqt breeze-icons sddm
    install_services
    systemctl enable sddm.service
    ;;
"openbox")
    install_xorg
    install_pkg openbox obconf xterm lightdm lightdm-gtk-greeter
    install_services
    systemctl enable lightdm.service
    ;;
"awesome")
    install_xorg
    install_pkg awesome vicious xterm lightdm lightdm-gtk-greeter
    install_services
    systemctl enable lightdm.service
    ;;
"minimal")
    install_xorg
    ;;
"i3")
    install_xorg
    install_pkg i3-wm i3blocks i3lock i3status dmenu rxvt-unicode lightdm lightdm-gtk-greeter
    install_services
    systemctl enable lightdm.service
    ;;
"i3-gaps")
    install_xorg
    install_pkg i3-gaps i3blocks i3lock i3status dmenu rxvt-unicode lightdm lightdm-gtk-greeter
    install_services
    systemctl enable lightdm.service
    ;;
"deepin")
    install_xorg
    install_pkg deepin deepin-extra deepin-kwin
    install_services
    sed -i 's/^#greeter-session=.*/greeter-session=lightdm-deepin-greeter/' /etc/lightdm/lightdm.conf
    systemctl enable lightdm.service
    ;;
"budgie")
    install_xorg
    install_pkg budgie-desktop budgie-desktop-view budgie-screensaver gnome-control-center network-manager-applet gnome
    install_services
    systemctl enable gdm.service
    ;;
*)
    echo "Unsupported desktop environment"
    exit 0
    ;;

esac

# determine processor type and install microcode
PROC_TYPE="$(lscpu | grep "Vendor ID:" | awk '{print $3}' | head -1)"

case "$PROC_TYPE" in
"GenuineIntel")
    install_pkg intel-ucode
    IMG=intel-ucode.img
    ;;
"AuthenticAMD")
    install_pkg amd-ucode
    IMG=amd-ucode.img
    ;;
*)
    echo "ERROR: Unknown processor type"
    exit 0
    ;;
esac

echo "Installing Graphics Drivers"
# Graphics Drivers find and install
if [[ "$(lspci | grep -E '(NVIDIA|GeForce)' -c)" -gt "0" ]]; then
    install_pkg "nvidia nvidia-utils libglvnd"
elif [[ "$(lspci | grep -E '(Radeon|AMD)' -c)" -gt "0" ]]; then
    install_pkg "xf86-video-amdgpu mesa-libgl mesa-vdpau libvdpau-va-gl"
elif [[ "$(lspci | grep -E '(Integrated Graphics Controller|Intel Corporation UHD)' -c)" -gt "0" ]]; then
    # install_pkg "libva-intel-driver libvdpau-va-gl lib32-vulkan-intel vulkan-intel libva-intel-driver libva-utils lib32-mesa"
    install_pkg "xf86-video-intel vulkan-radeon mesa-libgl mesa-vdpau libvdpau-va-gl"
else
    echo "No graphics card found!"
fi

PART_UUID=$(blkid -s UUID -o value "$PART2")
PART_UUID=$(blkid -s PARTUUID -o value "$PART2")

case "$BOOTLOADER" in
"grub")
    echo "Installing GRUB"
    install_pkg grub os-prober
    if [[ "$LAYOUT" =~ "luks" ]]; then
        echo "Installing GRUB for LUKS"
        sed -i -e 's/GRUB_CMDLINE_LINUX="\(.\+\)"/GRUB_CMDLINE_LINUX="\1 cryptdevice=UUID='"${PART_UUID}"':luks"/g' -e 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cryptdevice=UUID='"${PART_UUID}"':luks"/g' /etc/default/grub
    fi
    if [[ "$UEFI" -eq 1 ]]; then
        grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=ArchTitus
    else
        grub-install --target=i386-pc "$DISK"
    fi
    grub-mkconfig -o /boot/grub/grub.cfg
    ;;
"systemd")
    if [[ "$UEFI" -eq 1 ]]; then
        echo "Installing systemd-boot"
        bootctl --path=/boot install
        case "$LAYOUT" in
        "btrfs")
            echo -e "title\tArchTitus\nlinux\t/vmlinuz-linux\ninitrd\t/initramfs-linux.img\ninitrd\t/$IMG\noptions\troot=PARTUUID=$PART_UUID rw rootflags=subvol=@" >/boot/loader/entries/arch.conf
            ;;
        "lvm")
            echo -e "title\tArchTitus\nlinux\t/vmlinuz-linux\ninitrd\t/initramfs-linux.img\ninitrd\t/$IMG\noptions\troot=/dev/$LVM_VG/${LVM_NAMES[0]} rw" >/boot/loader/entries/arch.conf
            ;;
        "luks")
            echo -e "title\tArchTitus\nlinux\t/vmlinuz-linux\ninitrd\t/initramfs-linux.img\ninitrd\t/$IMG\noptions\tcryptdevice=UUID=$PART_UUID:luks root=/dev/$LVM_VG/${LVM_NAMES[0]} rw" >/boot/loader/entries/arch.conf
            ;;
        "none")
            echo -e "title\tArchTitus\nlinux\t/vmlinuz-linux\ninitrd\t/initramfs-linux.img\ninitrd\t/$IMG\noptions\troot=PARTUUID=$PART_UUID rw" >/boot/loader/entries/arch.conf
            ;;
        *)
            echo "ERROR! Systemd-boot is not supported for BIOS systems"
            exit 0
            ;;
        esac
        echo -e "default  arch\ntimeout\t5" >/boot/loader/loader.conf
    fi
    ;;
"efistub")
    if [[ "$UEFI" -eq 1 ]]; then
        echo "Installing efistub"
        case "$LAYOUT" in
        "btrfs")
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus-Fallback" --loader "/vmlinuz-linux" --unicode "root=PARTUUID=$PART_UUID rw rootflags=subvol=@ initrd=\\$IMG initrd=\initramfs-linux-fallback.img"
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus" --loader "/vmlinuz-linux" --unicode "root=PARTUUID=$PART_UUID rw rootflags=subvol=@ initrd=\\$IMG initrd=\initramfs-linux.img"
            ;;
        "lvm")
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus-Fallback" --loader "/vmlinuz-linux" --unicode "root=/dev/$LVM_VG/${LVM_NAMES[0]} rw initrd=\\$IMG initrd=\initramfs-linux-fallback.img"
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus" --loader "/vmlinuz-linux" --unicode "root=/dev/$LVM_VG/${LVM_NAMES[0]} rw initrd=\\$IMG initrd=\initramfs-linux.img"
            ;;
        "luks")
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus-Fallback" --loader "/vmlinuz-linux" --unicode "cryptdevice=PARTUUID=$PART_UUID:luks:allow-discards root=/dev/$LVM_VG/${LVM_NAMES[0]} rw initrd=\\$IMG initrd=\initramfs-linux-fallback.img"
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus" --loader "/vmlinuz-linux" --unicode "cryptdevice=PARTUUID=$PART_UUID:luks:allow-discards root=/dev/$LVM_VG/${LVM_NAMES[0]} rw initrd=\\$IMG initrd=\initramfs-linux.img"
            ;;
        "none")
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus-Fallback" --loader "/vmlinuz-linux" --unicode "root=PARTUUID=$PART_UUID rw initrd=\\$IMG initrd=\initramfs-linux-fallback.img"
            efibootmgr --disk "$DISK" --part 1 --create --label "ArchTitus" --loader "/vmlinuz-linux" --unicode "root=PARTUUID=$PART_UUID rw initrd=\\$IMG initrd=\initramfs-linux.img"
            ;;
        *)
            echo "ERROR! efistub is not supported for BIOS systems"
            exit 0
            ;;
        esac
    fi
    ;;
"none")
    echo "Skipping bootloader installation"
    ;;
*)
    echo "ERROR! Unknown bootloader"
    exit 0
    ;;
esac

echo "Adding User and hostname"
if [ "$(id -u)" -eq "0" ]; then
    useradd -m -G wheel -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    if [[ "$DESKTOP" != "minimal" ]]; then
        cp -R "$SCRIPT_DIR" /home/"$USERNAME"/
        chown -R "$USERNAME": /home/"$USERNAME"/asai
    fi
    echo "$HOSTNAME" >>/etc/hostname
else
    echo "You are already a user proceed with aur installs"
fi
case "$LAYOUT" in
"lvm")
    echo "LVM hooks added"
    sed -i "/^HOOK/s/filesystems/${HOOKS[*]}/" /etc/mkinitcpio.conf
    ;;
"luks")
    echo "LUKS hooks added"
    sed -i "s/^HOOK.*/HOOKS=(${HOOKS[*]})/" /etc/mkinitcpio.conf
    ;;
"none")
    echo "Skipping hooks addition"
    ;;
*)
    echo "ERROR! No hooks added"
    exit 0
    ;;
esac

if [[ "$FS" =~ "btrfs" ]]; then
        echo "Btrfs module added"
        sed -i '/^MODULES=/s/(/(btrfs/' /etc/mkinitcpio.conf
fi

if [[ -f "/etc/mkinitcpio.conf" ]]; then
    # making mkinitcpio with linux kernel
    echo "Building initramfs"
    mkinitcpio -p linux
fi

title "System ready for 2-user.sh"
