#!/usr/bin/env bash
# shellcheck disable=SC1090

SCRIPT_DIR="$HOME/asai"

CONFIG_FILE="$SCRIPT_DIR"/configs/setup

source_setup() {
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
    else
        echo "ERROR! Missing file: $CONFIG_FILE"
        exit 0
    fi
}

source_setup

title "Installing AUR helper"

cd "$HOME" || exit 0
case "$AURHELPER" in
"yay")
    install_pkg "go"
    git clone "https://aur.archlinux.org/yay.git"
    ;;
"trizen")
    install_pkg "perl"
    git clone "https://aur.archlinux.org/trizen.git"
    ;;
"aurman")
    git clone "https://aur.archlinux.org/aurman.git"
    ;;
"aura")
    install_pkg "stack"
    git clone "https://aur.archlinux.org/aura.git"
    ;;
"pikaur")
    git clone "https://aur.archlinux.org/pikaur.git"
    ;;
"none") ;;

*)
    echo "ERROR! Invalid AUR helper"
    ;;
esac
if [[ "$AURHELPER" != "none" ]]; then
    cd "$AURHELPER" || exit 0
    makepkg -si --noconfirm
    cd "$HOME" || exit 0
fi

case "$DESKTOP" in
"lxqt")
    install_aur sddm-nordic-theme-git
    ;;
"kde")
    install_aur sddm-nordic-theme-git
    ;;
"awesome")
    install_aur rofi picom i3lock-fancy xclip ttf-roboto polkit-gnome materia-theme lxappearance flameshot pnmixer network-manager-applet xfce4-power-manager qt5-styleplugins papirus-icon-theme
    git clone "https://github.com/ChrisTitusTech/titus-awesome" "$HOME"/.config/awesome
    mkdir -p "$HOME"/.config/rofi
    cp "$HOME"/.config/awesome/theme/config.rasi "$HOME"/.config/rofi/config.rasi
    sed -i "/@import/c\@import $HOME/.config/awesome/theme/sidebar.rasi" "$HOME"/.config/rofi/config.rasi
    ;;
esac

export PATH=$PATH:$HOME/.local/bin

title "System ready for 3-post-setup.sh"
