#!/usr/bin/env bash
# shellcheck disable=SC1090

SCRIPT_DIR="$HOME/asai"

FUNC_FILE="$SCRIPT_DIR"/configs/shared
CONFIG_FILE="$SCRIPT_DIR"/configs/setup.conf

source_file() {
    if [[ -f "$1" ]]; then
        source "$1"
    else
        echo "ERROR! Missing file: $1"
        exit 0
    fi
}

source_file "$FUNC_FILE"
source_file "$CONFIG_FILE"

install_grub_theme() {
    if [[ "$GRUBTHEME" =~ "None" ]]; then
        echo "Skipping GRUB theme installation"
    else
        echo -e "Installing $GRUBTHEME Grub theme..."
        git clone https://github.com/ChrisTitusTech/Top-5-Bootloader-Themes "$HOME"/tmp
        mkdir -p "$THEMEDIR"/"$GRUBTHEME"
        cp -a "$HOME"/tmp/themes/"$GRUBTHEME"/* "$THEMEDIR"/"$GRUBTHEME"
        cp -an /etc/default/grub /etc/default/grub.bak
        grep "GRUB_THEME=" /etc/default/grub >/dev/null 2>&1 && sed -i '/GRUB_THEME=/d' /etc/default/grub
        echo "GRUB_THEME=\"$THEMEDIR/$GRUBTHEME/theme.txt\"" >>/etc/default/grub
        echo -e "Updating grub..."
        grub-mkconfig -o /boot/grub/grub.cfg
    fi
}

title "Post Install and cleaning"
if [[ "$BOOTLOADER" =~ "grub" ]]; then
    install_grub_theme
fi

if [[ "$DESKTOP" =~ "lxqt" || "$DESKTOP" =~ "kde" ]]; then
    echo "Setting up SDDM Theme"
    cat <<EOF >/etc/sddm.conf
[Theme]
Current=Nordic
EOF
fi

echo "Enabling Essential Services"
systemctl enable cups.service
systemctl enable cronie.service
ntpd -qg
systemctl enable ntpd.service
systemctl stop dhcpcd.service
systemctl disable dhcpcd.service
systemctl enable NetworkManager.service
systemctl enable bluetooth

echo "Cleaning"
sudo_password "/etc/sudoers"

rm -r /root/asai
rm -r /home/"$USERNAME"/asai

# Replace in the same state
cd "$(pwd)" || exit 0
