#!/usr/bin/env bash
# shellcheck disable=SC1090

SCRIPT_DIR="$HOME/asai"

CONFIG_FILE="$SCRIPT_DIR"/configs/setup.conf

source_setup() {
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
    else
        echo "ERROR! Missing file: $CONFIG_FILE"
        exit 0
    fi
}

source_setup

install_grub_theme() {
    if [[ "$GRUBTHEME" != "None" ]]; then
        echo -e "Installing $GRUBTHEME Grub theme..."
        git clone https://github.com/mfgbhatti/grub-themes "$HOME"/tmp
        mkdir -p "$THEMEDIR"/"${GRUBTHEME}"
        cp -a "$HOME"/tmp/themes/"$GRUBTHEME"/* "$THEMEDIR"/"$GRUBTHEME"
        cp -an /etc/default/grub /etc/default/grub.bak
        grep "GRUB_THEME=" /etc/default/grub >/dev/null 2>&1 && sed -i '/GRUB_THEME=/d' /etc/default/grub
        echo "GRUB_THEME=\"$THEMEDIR/$GRUBTHEME/theme.txt\"" >>/etc/default/grub
        echo -e "Updating grub..."
        grub-mkconfig -o /boot/grub/grub.cfg
    fi
}

title "Post Install and cleaning"
if [[ "$BOOTLOADER" =~ "grub" ]]; then
    install_grub_theme
fi

if [[ "$DESKTOP" =~ "lxqt" || "$DESKTOP" =~ "kde" ]]; then
    echo "Setting up SDDM Theme"
    cat <<EOF >/etc/sddm.conf
[Theme]
Current=Nordic
EOF
fi

echo "Enabling Essential Services"
for i in "${SERVICES[@]}"; do
    systemctl enable "$i".service
done
ntpd -qg
systemctl stop dhcpcd.service
systemctl disable dhcpcd.service

echo "Cleaning"
sudo_password "/etc/sudoers"

rm -r /root/asai
rm -r /home/"$USERNAME"/asai

# Replace in the same state
cd "$(pwd)" || exit 0
